name: internet_banking
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  card_swiper: ^3.0.1
  dart_jsonwebtoken: ^2.8.2
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  provider: ^6.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/img/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: 'assets/app.png'