name: Build app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Install dependencies
      run: npm install
      working-directory: Internet-banking-API

    - name: Build
      run: npm run build
      working-directory: Internet-banking-API

    - name: Depoly
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: main
        folder: Internet-banking-API/dist
